### ISSUE TITLE
How to set the access token?

### ISSUE THREAD

**Issue by yvanvds** [NAXAM/xf-mapbox#1]
Hey

Thanks for sharing this. I'm just testing your code and while there are no errors, i just get a blank screen. But of course I need to set the access token. I know how to do this with the the mapbox api provided by xamarin, but not with this api. 

Of course this is a pre-release, so I understand the documentation is not ready yet. But since i've done some work with mapbox before, i thought i might get it running if I just know how to set the access token.

**Comment by yvanvds** [comment]
Ok, just realized that this project also includes a demo. And it shows how to set the access token.

**Comment by kanvuduc** [comment]
Hi,

Thank you for using our library.

Cheers.
