### ISSUE TITLE
Problems with Xamarin.Forms implementation

### ISSUE THREAD

**Issue by charlenni** [NAXAM/xf-mapbox#2]
Again, thank you for your great work.

I downloaded the Xamarin.Forms implementation and get the following problems:

1. In the iOS renderer (MapViewRenderer.cs) I get an error in line 747. I assume, that there is a problem. The part is 
````
 if (Element.MapStyle.CustomLayers is INotifyCollectionChanged notifiyCollection)
 {
   notifiyCollection.CollectionChanged += OnLayersCollectionChanged;
 }
````
Should the code be 
````
 if (Element.MapStyle.CustomLayers is INotifyCollectionChanged)
 {
   var notifiyCollection = Element.MapStyle.CustomSources as INotifyCollectionChanged;
   notifiyCollection.CollectionChanged += OnLayersCollectionChanged;
 }
````
2. When compiling the demo for Android, I get the following error:
````
The "Xamarin.Build.Download.XamarinBuildAndroidAarProguardConfigs" task could not 
be loaded from the assembly S:\Entwicklung\xf-mapbox-master\packages\Xamarin.Build.Download.0.4.6\build\Xamarin.Build.Download.dll.  
Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are 
available, and that the task contains a public class that implements 
Microsoft.Build.Framework.ITask.
````
3. If I want to update to Naxam.Mapbox.Droid 5.1.0.1 as you suggested, than I get an error, because it needs Naxam.Mapzen.Lost.Droid 1.1.1

Perhaps I'm doing something wrong, but I downloaded only the project and tried to start the demo.

Thank you very much for your help.

**Comment by kanvuduc** [comment]
Issue 1: Plz make sure your IDE is update to date. That's C# 7 syntax.

Issue 2: Plz try again, I updated the code to use Mapbox Android 5.1.0

**Comment by charlenni** [comment]
Ok, thank you for your answer.

1. I use up to now VS 2015 with C# 6
2. and 3. are vanished with the new version.
