### ISSUE TITLE
Setting position at startup (Android)

### ISSUE THREAD

**Issue by charlenni** [NAXAM/xf-mapbox#3]
Coordinates which are set in XAML aren't shown at startup. If you set a new position later, it isn't a problem.

I assume, that the position and zoom should be set again in the OnMapReady event like

````
            map.CameraPosition = new CameraPosition.Builder()
                .Target(new LatLng(Element.Center.Lat, Element.Center.Long))
                .Zoom(Element.ZoomLevel)
                .Build();
````

I use the news version on Android simulator.

**Comment by kanvuduc** [comment]
Yeah, that's right. Could you plz make a pull request?

**Comment by kanvuduc** [comment]
Commit c34da6982ea35adddbe1fe5f96add8a77afa6784
