### ISSUE TITLE
Android not building pre96

### ISSUE THREAD

**Issue by heraknos** [NAXAM/xf-mapbox#8]
error: cannot find symbol com.mapbox.mapboxsdk.maps.MapboxMap.OnCameraIdleListener
  symbol:   class OnCameraIdleListener
  location: class MapboxMap	testMapBox.Android	...\testMapBox.Android\obj\Debug\android\src\mono\com\mapbox\mapboxsdk\maps\MapboxMap_OnCameraIdleListenerImplementor.java	

I try to run the sample you've done but I've got this error. If i try to install mapboxSDK android, I have java conflict.

This bug comes with 6 more, OnCamera...Listener

**Comment by kanvuduc** [comment]
Plz make sure your dev machine is up-to-date. Then clean and build the code. I have no issue.

Cheers.

**Comment by heraknos** [comment]
I clean the project, and now I have 
Error java.lang.IllegalArgumentException: already added :  Lokio/AsyncTimeout;	testMapBox.Android

**Comment by heraknos** [comment]
After full Nugget re-installation, it works.
God, Xamarin is so bugged by dependences ...

**Comment by albertoms** [comment]
@heraknos when you say "full Nugget re-installation" you mean to delete and reinstall all the packages needed for your app (one by one)? I'm facing the Exception issue right now.

**Comment by kanvuduc** [comment]
It's better to add the library by Nuget package, then copy the code over if you need. Otherwise, just use it in your project. 

Cheers.

**Comment by albertoms** [comment]
This problem ocurred in my project, but in the end, I managed to compile it by deleting references and add them again.
